---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  hadolint:
    name: hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.2
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
