---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
